sudo: false
language: node_js
node_js:
- '8'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm test
- npm run coveralls
deploy:
  provider: heroku
  api_key:
    secure: dU5VYUJcDHE5JlAlkFEGkWYrfJre9GhDRVT812iU/70IARzT2EcjEmyRaPSZ1bI/cZwbRJ8PPZOXWSPR3sOYQgxDX/KmxA9tfH9fyyZ9f+MLBxl3bq7iJgZrwdNkaf/0wEA+GU6U5F/xU3+CFfQs67imH54Siosp96It2EzMg0s8TducY8jPSNG3ifBRPFKQEJe7ZwXMBpgF0vX38XSMPlNNrOrdrlEGfp7dP34gC4yn+Rl6H5x6sGsj/61ESvKdnPfhMWqRFexlrnMab4LVa5NtmjbZj1CFSAQD6G4W0ZfvGSKAPWTx7aS+HRnJTIGCIYWnkMRoEpc6rpspi36ad6FJKAejoVGMl1KpHNf52jcJNqOz2BjVq9iLZsOmYgrgJ48Jm0B+C4DGXWukk/Ao6cQgOMXSRUEee3ZryuNlZap4wjssaPSf8HwgUmyEkMLoOaOQh9Ta5SFz1fR9OuT1ffy7rLnO+lO+Z7CGKVhEYCC2QeAoboN1VnwKlbA/5EvuUOqCOcMPE1+qmgVuwlq9dEovr1z6HtA1kGmsFlodSo1ST6VmT1qXZBfkGoO9bsN6u6/1nsOU5Xadf40caXCffY59RdHr1P0uFvkPu8nLw15vpuZzTiLLXfyGqqbpLq4B+CNOtupPBFhZgi6TneOM+DB4CAwT3o+xiuv4StaOLfE=
  app: calorie-counts
